/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_8_jacektracz_tutorial;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
