/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_8_jacektracz_tutorial;

import org.junit.Test;

import com.jacektracz.java8.starter.Library;

import static org.junit.Assert.*;

public class LibraryTest {
	@Test public void gg() {

	}
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
