import sys
import os
from .. DBG_AdapterBase import *
        
        
class DBG_scsiopMap(DBG_AdapterBase):
        def __init__(self,spar):                
                DBG_AdapterBase.__init__(self,spar)
                self.xx_dbg("DBG_SrbFunctions::__init__::in::")
                self.xx_set_class_name ( "DBG_SrbFunctions" )
                self.xx_set_full_class_name ( "iastora!Wcdl::Chipset" )
                self.xx_dbg("DBG_Chipset::__init__::out")
                self.srb_scsiop_map = {}
                
        def create_map(self):            

            # 6-byte commands:
            
            self.srb_scsiop_map[0x00] = 'SCSIOP_TEST_UNIT_READY'
            self.srb_scsiop_map[0x01] = 'SCSIOP_REZERO_UNIT'
            self.srb_scsiop_map[0x01] = 'SCSIOP_REWIND'
            self.srb_scsiop_map[0x02] = 'SCSIOP_REQUEST_BLOCK_ADDR'
            self.srb_scsiop_map[0x03] = 'SCSIOP_REQUEST_SENSE'
            self.srb_scsiop_map[0x04] = 'SCSIOP_FORMAT_UNIT'
            self.srb_scsiop_map[0x05] = 'SCSIOP_READ_BLOCK_LIMITS'
            self.srb_scsiop_map[0x07] = 'SCSIOP_REASSIGN_BLOCKS'
            self.srb_scsiop_map[0x07] = 'SCSIOP_INIT_ELEMENT_STATUS'
            self.srb_scsiop_map[0x08] = 'SCSIOP_READ6'
            self.srb_scsiop_map[0x08] = 'SCSIOP_RECEIVE'
            self.srb_scsiop_map[0x0A] = 'SCSIOP_WRITE6'
            self.srb_scsiop_map[0x0A] = 'SCSIOP_PRINT'
            self.srb_scsiop_map[0x0A] = 'SCSIOP_SEND'
            self.srb_scsiop_map[0x0B] = 'SCSIOP_SEEK6'
            self.srb_scsiop_map[0x0B] = 'SCSIOP_TRACK_SELECT'
            self.srb_scsiop_map[0x0B] = 'SCSIOP_SLEW_PRINT'
            self.srb_scsiop_map[0x0B] = 'SCSIOP_SET_CAPACITY'
            self.srb_scsiop_map[0x0C] = 'SCSIOP_SEEK_BLOCK'
            self.srb_scsiop_map[0x0D] = 'SCSIOP_PARTITION'
            self.srb_scsiop_map[0x0F] = 'SCSIOP_READ_REVERSE'
            self.srb_scsiop_map[0x10] = 'SCSIOP_WRITE_FILEMARKS'
            self.srb_scsiop_map[0x10] = 'SCSIOP_FLUSH_BUFFER'
            self.srb_scsiop_map[0x11] = 'SCSIOP_SPACE'
            self.srb_scsiop_map[0x12] = 'SCSIOP_INQUIRY'
            self.srb_scsiop_map[0x13] = 'SCSIOP_VERIFY6'
            self.srb_scsiop_map[0x14] = 'SCSIOP_RECOVER_BUF_DATA'
            self.srb_scsiop_map[0x15] = 'SCSIOP_MODE_SELECT'
            self.srb_scsiop_map[0x16] = 'SCSIOP_RESERVE_UNIT'
            self.srb_scsiop_map[0x17] = 'SCSIOP_RELEASE_UNIT'
            self.srb_scsiop_map[0x18] = 'SCSIOP_COPY'
            self.srb_scsiop_map[0x19] = 'SCSIOP_ERASE'
            self.srb_scsiop_map[0x1A] = 'SCSIOP_MODE_SENSE'
            self.srb_scsiop_map[0x1B] = 'SCSIOP_START_STOP_UNIT'
            self.srb_scsiop_map[0x1B] = 'SCSIOP_STOP_PRINT'
            self.srb_scsiop_map[0x1B] = 'SCSIOP_LOAD_UNLOAD'
            self.srb_scsiop_map[0x1C] = 'SCSIOP_RECEIVE_DIAGNOSTIC'
            self.srb_scsiop_map[0x1D] = 'SCSIOP_SEND_DIAGNOSTIC'
            self.srb_scsiop_map[0x1E] = 'SCSIOP_MEDIUM_REMOVAL'
            
            # 10-byte commands
            self.srb_scsiop_map[0x23] = 'SCSIOP_READ_FORMATTED_CAPACITY'
            self.srb_scsiop_map[0x25] = 'SCSIOP_READ_CAPACITY'
            self.srb_scsiop_map[0x28] = 'SCSIOP_READ'
            self.srb_scsiop_map[0x2A] = 'SCSIOP_WRITE'
            self.srb_scsiop_map[0x2B] = 'SCSIOP_SEEK'
            self.srb_scsiop_map[0x2B] = 'SCSIOP_LOCATE'
            self.srb_scsiop_map[0x2B] = 'SCSIOP_POSITION_TO_ELEMENT'
            self.srb_scsiop_map[0x2E] = 'SCSIOP_WRITE_VERIFY'
            self.srb_scsiop_map[0x2F] = 'SCSIOP_VERIFY'
            self.srb_scsiop_map[0x30] = 'SCSIOP_SEARCH_DATA_HIGH'
            self.srb_scsiop_map[0x31] = 'SCSIOP_SEARCH_DATA_EQUAL'
            self.srb_scsiop_map[0x32] = 'SCSIOP_SEARCH_DATA_LOW'
            self.srb_scsiop_map[0x33] = 'SCSIOP_SET_LIMITS'
            self.srb_scsiop_map[0x34] = 'SCSIOP_READ_POSITION'
            self.srb_scsiop_map[0x35] = 'SCSIOP_SYNCHRONIZE_CACHE'
            self.srb_scsiop_map[0x39] = 'SCSIOP_COMPARE'
            self.srb_scsiop_map[0x3A] = 'SCSIOP_COPY_COMPARE'
            self.srb_scsiop_map[0x3B] = 'SCSIOP_WRITE_DATA_BUFF'
            self.srb_scsiop_map[0x3C] = 'SCSIOP_READ_DATA_BUFF'
            self.srb_scsiop_map[0x3F] = 'SCSIOP_WRITE_LONG'
            self.srb_scsiop_map[0x40] = 'SCSIOP_CHANGE_DEFINITION'
            self.srb_scsiop_map[0x41] = 'SCSIOP_WRITE_SAME'
            self.srb_scsiop_map[0x42] = 'SCSIOP_READ_SUB_CHANNEL'
            self.srb_scsiop_map[0x42] = 'SCSIOP_UNMAP'
            self.srb_scsiop_map[0x43] = 'SCSIOP_READ_TOC'
            self.srb_scsiop_map[0x44] = 'SCSIOP_READ_HEADER'
            self.srb_scsiop_map[0x44] = 'SCSIOP_REPORT_DENSITY_SUPPORT'
            self.srb_scsiop_map[0x45] = 'SCSIOP_PLAY_AUDIO'
            self.srb_scsiop_map[0x46] = 'SCSIOP_GET_CONFIGURATION'
            self.srb_scsiop_map[0x47] = 'SCSIOP_PLAY_AUDIO_MSF'
            self.srb_scsiop_map[0x48] = 'SCSIOP_PLAY_TRACK_INDEX'
            self.srb_scsiop_map[0x48] = 'SCSIOP_SANITIZE'
            self.srb_scsiop_map[0x49] = 'SCSIOP_PLAY_TRACK_RELATIVE'
            self.srb_scsiop_map[0x4A] = 'SCSIOP_GET_EVENT_STATUS'
            self.srb_scsiop_map[0x4B] = 'SCSIOP_PAUSE_RESUME'
            self.srb_scsiop_map[0x4C] = 'SCSIOP_LOG_SELECT'
            self.srb_scsiop_map[0x4D] = 'SCSIOP_LOG_SENSE'
            self.srb_scsiop_map[0x4E] = 'SCSIOP_STOP_PLAY_SCAN'
            self.srb_scsiop_map[0x50] = 'SCSIOP_XDWRITE'
            self.srb_scsiop_map[0x51] = 'SCSIOP_XPWRITE'
            self.srb_scsiop_map[0x51] = 'SCSIOP_READ_DISK_INFORMATION'
            self.srb_scsiop_map[0x51] = 'SCSIOP_READ_DISC_INFORMATION'
            self.srb_scsiop_map[0x52] = 'SCSIOP_READ_TRACK_INFORMATION'
            self.srb_scsiop_map[0x53] = 'SCSIOP_XDWRITE_READ'
            self.srb_scsiop_map[0x53] = 'SCSIOP_RESERVE_TRACK_RZONE'
            self.srb_scsiop_map[0x54] = 'SCSIOP_SEND_OPC_INFORMATION'
            self.srb_scsiop_map[0x55] = 'SCSIOP_MODE_SELECT10'
            self.srb_scsiop_map[0x56] = 'SCSIOP_RESERVE_UNIT10'
            self.srb_scsiop_map[0x56] = 'SCSIOP_RESERVE_ELEMENT'
            self.srb_scsiop_map[0x57] = 'SCSIOP_RELEASE_UNIT10'
            self.srb_scsiop_map[0x57] = 'SCSIOP_RELEASE_ELEMENT'
            self.srb_scsiop_map[0x58] = 'SCSIOP_REPAIR_TRACK'
            self.srb_scsiop_map[0x5A] = 'SCSIOP_MODE_SENSE10'
            self.srb_scsiop_map[0x5B] = 'SCSIOP_CLOSE_TRACK_SESSION'
            self.srb_scsiop_map[0x5C] = 'SCSIOP_READ_BUFFER_CAPACITY'
            self.srb_scsiop_map[0x5D] = 'SCSIOP_SEND_CUE_SHEET'
            self.srb_scsiop_map[0x5E] = 'SCSIOP_PERSISTENT_RESERVE_IN'
            self.srb_scsiop_map[0x5F] = 'SCSIOP_PERSISTENT_RESERVE_OUT'
            
            # 12-byte commands
            self.srb_scsiop_map[0xA0] = 'SCSIOP_REPORT_LUNS'
            self.srb_scsiop_map[0xA1] = 'SCSIOP_BLANK'
            self.srb_scsiop_map[0xA1] = 'SCSIOP_ATA_PASSTHROUGH12'
            self.srb_scsiop_map[0xA2] = 'SCSIOP_SEND_EVENT'
            self.srb_scsiop_map[0xA2] = 'SCSIOP_SECURITY_PROTOCOL_IN'
            self.srb_scsiop_map[0xA3] = 'SCSIOP_SEND_KEY'
            self.srb_scsiop_map[0xA3] = 'SCSIOP_MAINTENANCE_IN'
            self.srb_scsiop_map[0xA4] = 'SCSIOP_REPORT_KEY'
            self.srb_scsiop_map[0xA4] = 'SCSIOP_MAINTENANCE_OUT'
            self.srb_scsiop_map[0xA5] = 'SCSIOP_MOVE_MEDIUM'
            self.srb_scsiop_map[0xA6] = 'SCSIOP_LOAD_UNLOAD_SLOT'
            self.srb_scsiop_map[0xA6] = 'SCSIOP_EXCHANGE_MEDIUM'
            self.srb_scsiop_map[0xA7] = 'SCSIOP_SET_READ_AHEAD'
            self.srb_scsiop_map[0xA7] = 'SCSIOP_MOVE_MEDIUM_ATTACHED'
            self.srb_scsiop_map[0xA8] = 'SCSIOP_READ12'
            self.srb_scsiop_map[0xA8] = 'SCSIOP_GET_MESSAGE'
            self.srb_scsiop_map[0xA9] = 'SCSIOP_SERVICE_ACTION_OUT12'
            self.srb_scsiop_map[0xAA] = 'SCSIOP_WRITE12'
            self.srb_scsiop_map[0xAB] = 'SCSIOP_SEND_MESSAGE'
            self.srb_scsiop_map[0xAB] = 'SCSIOP_SERVICE_ACTION_IN12'
            self.srb_scsiop_map[0xAC] = 'SCSIOP_GET_PERFORMANCE'
            self.srb_scsiop_map[0xAD] = 'SCSIOP_READ_DVD_STRUCTURE'
            self.srb_scsiop_map[0xAE] = 'SCSIOP_WRITE_VERIFY12'
            self.srb_scsiop_map[0xAF] = 'SCSIOP_VERIFY12'
            self.srb_scsiop_map[0xB0] = 'SCSIOP_SEARCH_DATA_HIGH12'
            self.srb_scsiop_map[0xB1] = 'SCSIOP_SEARCH_DATA_EQUAL12'
            self.srb_scsiop_map[0xB2] = 'SCSIOP_SEARCH_DATA_LOW12'
            self.srb_scsiop_map[0xB3] = 'SCSIOP_SET_LIMITS12'
            self.srb_scsiop_map[0xB4] = 'SCSIOP_READ_ELEMENT_STATUS_ATTACHED'
            self.srb_scsiop_map[0xB5] = 'SCSIOP_REQUEST_VOL_ELEMENT'
            self.srb_scsiop_map[0xB5] = 'SCSIOP_SECURITY_PROTOCOL_OUT'
            self.srb_scsiop_map[0xB6] = 'SCSIOP_SEND_VOLUME_TAG'
            self.srb_scsiop_map[0xB6] = 'SCSIOP_SET_STREAMING'
            self.srb_scsiop_map[0xB7] = 'SCSIOP_READ_DEFECT_DATA'
            self.srb_scsiop_map[0xB8] = 'SCSIOP_READ_ELEMENT_STATUS'
            self.srb_scsiop_map[0xB9] = 'SCSIOP_READ_CD_MSF'
            self.srb_scsiop_map[0xBA] = 'SCSIOP_SCAN_CD'
            self.srb_scsiop_map[0xBA] = 'SCSIOP_REDUNDANCY_GROUP_IN'
            self.srb_scsiop_map[0xBB] = 'SCSIOP_SET_CD_SPEED'
            self.srb_scsiop_map[0xBB] = 'SCSIOP_REDUNDANCY_GROUP_OUT'
            self.srb_scsiop_map[0xBC] = 'SCSIOP_PLAY_CD'
            self.srb_scsiop_map[0xBC] = 'SCSIOP_SPARE_IN'
            self.srb_scsiop_map[0xBD] = 'SCSIOP_MECHANISM_STATUS'
            self.srb_scsiop_map[0xBD] = 'SCSIOP_SPARE_OUT'
            self.srb_scsiop_map[0xBE] = 'SCSIOP_READ_CD'
            self.srb_scsiop_map[0xBE] = 'SCSIOP_VOLUME_SET_IN'
            self.srb_scsiop_map[0xBF] = 'SCSIOP_SEND_DVD_STRUCTURE'
            self.srb_scsiop_map[0xBF] = 'SCSIOP_VOLUME_SET_OUT'
            self.srb_scsiop_map[0xE7] = 'SCSIOP_INIT_ELEMENT_RANGE'
            
            # 16-byte commands
            self.srb_scsiop_map[0x80] = 'SCSIOP_XDWRITE_EXTENDED16'
            self.srb_scsiop_map[0x80] = 'SCSIOP_WRITE_FILEMARKS16'
            self.srb_scsiop_map[0x81] = 'SCSIOP_REBUILD16'
            self.srb_scsiop_map[0x81] = 'SCSIOP_READ_REVERSE16'
            self.srb_scsiop_map[0x82] = 'SCSIOP_REGENERATE16'
            self.srb_scsiop_map[0x83] = 'SCSIOP_EXTENDED_COPY'
            self.srb_scsiop_map[0x83] = 'SCSIOP_POPULATE_TOKEN'
            self.srb_scsiop_map[0x83] = 'SCSIOP_WRITE_USING_TOKEN'
            self.srb_scsiop_map[0x84] = 'SCSIOP_RECEIVE_COPY_RESULTS'
            self.srb_scsiop_map[0x84] = 'SCSIOP_RECEIVE_ROD_TOKEN_INFORMATION'
            self.srb_scsiop_map[0x85] = 'SCSIOP_ATA_PASSTHROUGH16'
            self.srb_scsiop_map[0x86] = 'SCSIOP_ACCESS_CONTROL_IN'
            self.srb_scsiop_map[0x87] = 'SCSIOP_ACCESS_CONTROL_OUT'
            self.srb_scsiop_map[0x88] = 'SCSIOP_READ16'
            self.srb_scsiop_map[0x8A] = 'SCSIOP_WRITE16'
            self.srb_scsiop_map[0x8C] = 'SCSIOP_READ_ATTRIBUTES'
            self.srb_scsiop_map[0x8D] = 'SCSIOP_WRITE_ATTRIBUTES'
            self.srb_scsiop_map[0x8E] = 'SCSIOP_WRITE_VERIFY16'
            self.srb_scsiop_map[0x8F] = 'SCSIOP_VERIFY16'
            self.srb_scsiop_map[0x90] = 'SCSIOP_PREFETCH16'
            self.srb_scsiop_map[0x91] = 'SCSIOP_SYNCHRONIZE_CACHE16'
            self.srb_scsiop_map[0x91] = 'SCSIOP_SPACE16'
            self.srb_scsiop_map[0x92] = 'SCSIOP_LOCK_UNLOCK_CACHE16'
            self.srb_scsiop_map[0x92] = 'SCSIOP_LOCATE16'
            self.srb_scsiop_map[0x93] = 'SCSIOP_WRITE_SAME16'
            self.srb_scsiop_map[0x93] = 'SCSIOP_ERASE16'
            self.srb_scsiop_map[0x9E] = 'SCSIOP_READ_CAPACITY16'
            self.srb_scsiop_map[0x9E] = 'SCSIOP_GET_LBA_STATUS'
            self.srb_scsiop_map[0x9E] = 'SCSIOP_SERVICE_ACTION_IN16'
            self.srb_scsiop_map[0x9F] = 'SCSIOP_SERVICE_ACTION_OUT16'

            # 32-byte commands
            self.srb_scsiop_map[0x7F] = 'SCSIOP_OPERATION32'

